#!/bin/sh

category=$1
bg="#0e0e0e"

date=$(date +%Y_%b_%d_%H%M%S)

getWallpaper() {
	
	local size='1920x1080'

	wget -O ~/repo/Wallpapers/$date.jpg https://source.unsplash.com/random/${size}?$category
}

setWallpaper() {
	nitrogen --save --set-zoom-fill ~/repo/Wallpapers/$date.jpg
}

setWal() {
	wal -c
	wal -b $bg -i ~/repo/Wallpapers/$date.jpg
}

echo "Downloading wallpaper"
getWallpaper
echo "Got the $category wallaper !"
# Use nitrogen
#setWallpaper &

# Use pywal
setWal
echo "All set!!"
